### ISSUE TITLE
[BUG] Delete the last request will close the main windows

### ISSUE THREAD

**Issue by NghiaTranUIT** [Get-API-App/Issue-Tracker#50]
### Description
- Delete the last request on the source list will close the main windows

### Expect
- If it's the last request on the source list, don't close the windows -> Show the Windows with empty view

**Comment by NghiaTranUIT** [comment]
https://github.com/Get-API-App/Issue-Tracker/assets/5878421/25f52dd0-73ac-4299-ac37-906b2c71d621

**Comment by NghiaTranUIT** [comment]
Fixed

**Comment by gabeins** [comment]
It's not fixed on `1.0.5`

https://github.com/Get-API-App/Issue-Tracker/assets/192261/1d6e8e30-5f98-4546-8101-c29ab229eaef

**Comment by gabeins** [comment]
It seems it doesn't happen consistently, see video of #52 where deleting the last request doesn't close the main window.
